### ISSUE TITLE
在windows平台编译成功后,测试失败

### ISSUE THREAD

**Issue by ioxuy** [avplayer/avpn#3]
运行信息
![QQ截图20190823114003](https://user-images.githubusercontent.com/7322644/63565428-8399ac80-c59b-11e9-8157-33decd3ffc4e.jpg)
路由表
![QQ截图20190823114048](https://user-images.githubusercontent.com/7322644/63565429-8399ac80-c59b-11e9-802b-3a89cf02a6e8.jpg)
控制面板网络连接信息
![QQ截图20190823114137](https://user-images.githubusercontent.com/7322644/63565431-84cad980-c59b-11e9-8d49-01726a61cb7a.jpg)

这是服务器截图,用的GOPROXY,是支持UDP的
![QQ截图20190823114246](https://user-images.githubusercontent.com/7322644/63565432-85fc0680-c59b-11e9-977b-09849dc84047.jpg)

**Comment by Jackarain** [comment]
请用 https://github.com/avplayer/socks_server
socks_server 实现了udp over tcp，和其它代理有所不同。

**Comment by ioxuy** [comment]
>

 请用 https://github.com/avplayer/socks_server
> socks_server 实现了udp over tcp，和其它代理有所不同。

**Comment by ioxuy** [comment]
> 请用 https://github.com/avplayer/socks_server
> socks_server 实现了udp over tcp，和其它代理有所不同。
谢谢回复!
可以在传一下socks_server的二进制文件吗?下载不成功
我尝试过重新编译,但是因为我这里boost环境有问题,也没编译成功
![QQ截图20190823135411](https://user-images.githubusercontent.com/7322644/63569900-c8c6da00-c5ad-11e9-8189-202ba3a9557c.jpg)

**Comment by Jackarain** [comment]
boost你可以使用
https://github.com/avplayer/boost
不需要搭boost环境，只要组织好cmake，就可以了，例如，在socks_server项目中的cmake中添加：

set(Boost_USE_STATIC_LIBS	ON)
set(Boost_USE_STATIC_RUNTIME	ON)

add_subdirectory(boost)
include_directories(boost)
link_libraries(Boost::system Boost::thread Boost::program_options Boost::regex Boost::locale Boost::random Boost::coroutine)

参考avpn中的cmake使用boost

**Comment by ioxuy** [comment]
嗯,好的.我编译过后测试成功了!谢谢作者
我在测试的时候遇到程序并没有设置适配器的地址,需要手动设置地址!
IP:10.0.0.1,mask:255.255.255.0,gateway:10.0.0.2,dns自定义!

**Comment by Jackarain** [comment]
是的，适配器的IP信息配置，以及路由相关配置，程序中都没有实现自动操作，欢迎提交相关patch

**Comment by microcai** [comment]
适配器的IP信息配置，以及路由相关配置，程序已经实现自动操作了， 欢迎使用。
